env: development

http_server:
  address: "0.0.0.0:8000"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "oravue"
  ssl_mode: "disable"

jwt:
  secret: "ifmt-developer"
  expiration: 3600