env: dev

http_server:
  address: "localhost:8000"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "oravue"
  sslmode: "disable"

jwt:
  secret: "your-secret-key"
  expiration: 3600